Sortable={create:function(data,metadata,target,style,selectable,sortable,paginate){var UNDEFINED_INDEX=-1;var ASCENDING_ORDER=1;var DESCENDING_ORDER=-1;var DEFAULT_PAGE_SIZE=10;var LEFT_SHIT=-1;var RIGHT_SHIFT=1;var _data=data||[];var _metadata=metadata||{};var _target=target||"";var _style=style||"";var _selectable=selectable||true;var _sortable=sortable||true;var _paginate=paginate||false;var _pageSizes=[5,10,25,50,100,250,500,1E3,5E3];var _pageSize=DEFAULT_PAGE_SIZE;var _currentPage=1;var _totalPages=
Math.ceil(_data.length/_pageSize);var _start=0;var _end=_start+_pageSize;var _paginationStart=1;var _paginationEnd=_totalPages;var _paginationViewSize=10;var _sortField=null;var _sortOrder=1;var _paginationTable="paginationTable";var _first="first";var _previous="previous";var _next="next";var _last="last";var _pageClass="page";var _pageSizeSelection="pageSize";var _table="#"+target;var _thead=_table+" thead";var _tbody=_table+" tbody";var _rows=_tbody+" tr";var _filters=null;var _filtered=[];var _currentSelecteRowIndex=
UNDEFINED_INDEX;var _currentSelectedRowPage=UNDEFINED_INDEX;var _columnSortIndex=UNDEFINED_INDEX;function getObjectKeys(object){var keys=[];if(object)for(var key in object)if(object.hasOwnProperty(key))keys.push(key);return keys}function getUnfilteredIndex(index){if(validateIndex(index)){var filteredSize=_filtered.length;if(filteredSize>0&&index<filteredSize)return _filtered[index]}return index}function validateIndex(index){if(typeof index==="number")return _filters?index>UNDEFINED_INDEX&&index<_filtered.length:
index>UNDEFINED_INDEX&&index<_data.length;return false}function getArrayIndex(position){return(_currentPage-1)*_pageSize+position}function compareFilteredValue(field,type,order){return function(first,second){var firstValue=_data[first][field];var secondValue=_data[second][field];switch(type){case "number":case "double":case "float":return(firstValue-secondValue)*order;case "date":var t1=(new Date(firstValue)).getTime();var t2=(new Date(secondValue)).getTime();var comparison=t1<t2?-1:t1>t2?1:0;return comparison*
order;case "string":default:var comparison=firstValue<secondValue?-1:firstValue>secondValue?1:0;return comparison*order}}}function compareValue(field,type,order){return function(firstItem,secondItem){var firstValue=firstItem[field];var secondValue=secondItem[field];switch(type){case "number":case "double":case "float":return(firstValue-secondValue)*order;case "date":var t1=(new Date(firstValue)).getTime();var t2=(new Date(secondValue)).getTime();var comparison=t1<t2?-1:t1>t2?1:0;return comparison*
order;case "string":default:var comparison=firstValue<secondValue?-1:firstValue>secondValue?1:0;return comparison*order}}}function goToPage(page){if(page!==undefined){_currentPage=page;_end=page*_pageSize;_start=_end-_pageSize;if(_filtered.length>0&&_end>_filtered.length)_end=_filtered.length;else if(_end>_data.length)_end=_data.length;refreshTableBody()}}function setPageSize(size){if(size!==undefined){_pageSize=size;_currentPage=UNDEFINED_INDEX;_currentSelecteRowIndex=UNDEFINED_INDEX;_currentSelectedRowPage=
UNDEFINED_INDEX;updatePagination();_paginationStart=1;goToPage(1)}}function updatePagination(){var itemCount=_filtered.length>0?_filtered.length:_data.length;_totalPages=_pageSize>itemCount?1:Math.ceil(itemCount/_pageSize);_paginationEnd=_totalPages}function shiftPagination(size,direction){if(size){var pageShift=size*direction;_paginationEnd+=pageShift;_paginationStart+=pageShift;if(_paginationStart<1){_paginationStart=1;_paginationEnd=_paginationViewSize}else if(_paginationEnd>_totalPages){_paginationEnd=
_totalPages;_paginationStart=_paginationEnd-_paginationViewSize}refreshPaginationView()}}function refreshPaginationView(){var table="<table id='"+_paginationTable+"'>";table+="<tr>";table+="<td>";table+="<select id='"+_pageSizeSelection+"'>";for(var i=0;i<_pageSizes.length;i++){var size=_pageSizes[i];if(size<_data.length){table+="<option value='"+size+"'";if(size===_pageSize)table+=" selected='selected'";table+=">";table+=size;table+="</option>"}else break}table+="<option value='"+_data.length+"'";
if(_pageSize>=_data.length)table+=" selected='selected'";table+=">All</option>";table+="</select>";table+="</td>";if(_currentPage!==1){table+="<td><span id='"+_first+"'> first</span></td>";table+="<td><span id='"+_previous+"'>previous</span></td>"}for(var i=_paginationStart;i<=_paginationEnd&&_totalPages>1;i++){table+="<td>";table+="<span class='"+_pageClass+"' id='"+("page_"+i)+"'>";if(i===_currentPage)table+="<b>"+i+"</b>";else table+=i;table+="</span></td>"}if(_currentPage!==_totalPages){table+=
"<td><span id='"+_next+"'> next</span></td>";table+="<td><span id='"+_last+"'>last</span></td>"}table+="</tr></table>";$("#"+_paginationTable).remove();$(_table).after(table);$("."+_pageClass).click(function(){var page=parseInt($(this).attr("id").split("_").pop());if(page!==_currentPage)goToPage(page)});$("#"+_first).click(function(){goToPage(1)});$("#"+_previous).click(function(){goToPage(_currentPage-1)});$("#"+_next).click(function(){goToPage(_currentPage+1)});$("#"+_last).click(function(){goToPage(_totalPages)});
$("#"+_pageSizeSelection).change(function(){var newSize=parseInt($(this).val());setPageSize(newSize)})}function resetFilters(){_filtered=[];_filters=null}function filter(filters){resetFilters();if(filters){var fields=[];for(var i=0;i<_metadata.length;i++){var entry=_metadata[i];var searchKey=entry.field;if(filters.hasOwnProperty(searchKey))fields[searchKey]=entry.type}if(!$.isEmptyObject(fields)){_filters=filters;_data.filter(function(element,index,array){var hasValue=false;for(var key in fields)if(fields.hasOwnProperty(key)){var type=
fields[key];var filterValue=filters[key];var itemValue=element[key];switch(type){case "number":case "double":case "float":hasValue=parseFloat(filterValue)-parseFloat(itemValue)==0;break;case "date":var t1=(new Date(filterValue)).getTime();var t2=(new Date(itemValue)).getTime();hasValue=t1===t2;break;case "string":filterValue=filterValue.toLowerCase();itemValue=itemValue.toLowerCase();if(itemValue.indexOf(filterValue)>UNDEFINED_INDEX)hasValue=true;else{filterValue=filterValue.split(" ");var size=filterValue.length;
var count=0;for(var i=0;i<size;i++){var value=filterValue[i];if(itemValue.indexOf(value)>UNDEFINED_INDEX)count++}hasValue=count===size}break}if(!hasValue)break}if(hasValue)_filtered.push(index)})}}}function selectableRow(table,row){row.click(function(){var newSelectedRowIndex=$(this).index();if(newSelectedRowIndex!==undefined)if(newSelectedRowIndex===_currentSelecteRowIndex){_currentSelecteRowIndex=UNDEFINED_INDEX;_currentSelectedRowPage=UNDEFINED_INDEX;$(this).removeClass(_style)}else{if(_currentSelecteRowIndex>
UNDEFINED_INDEX){var oldSelectedRow=$(_rows)[_currentSelecteRowIndex];$(oldSelectedRow).removeClass(_style)}_currentSelecteRowIndex=newSelectedRowIndex;_currentSelectedRowPage=_currentPage;$(this).addClass(_style)}})}function selectableTable(table){$(_rows).each(function(index){var row=$(this);selectableRow(table,row)})}function sortableTable(table){var headers=table+" th";$(headers).click(function(){var column=$(this).index();if(column!==undefined){var field=_metadata[column];if(field.field===_sortField)_sortOrder=
_sortOrder*DESCENDING_ORDER;else{_sortOrder=ASCENDING_ORDER;_sortField=field.field}sortByField(field,_sortOrder);if(_filters)setPageSize(_pageSize);else refreshTableBody()}})}function sortByField(metadataField,order){if(metadataField){var type=metadataField.type;var field=metadataField.field;if(_filters)_filtered.sort(compareFilteredValue(field,type,order));else{var selectedItem=null;if(_currentSelecteRowIndex!==UNDEFINED_INDEX)selectedItem=_data[_currentSelecteRowIndex];_data.sort(compareValue(field,
type,order));if(selectedItem)_currentSelecteRowIndex=_data.indexOf(selectedItem)}}}function appendRow(data){var row="<tr>";for(var i=0;i<_metadata.length;i++){var key=_metadata[i].field;row+="<td>"+data[key]+"</td>"}row+="</tr>";$(_tbody).append(row);if(_selectable)selectableRow(_table,$(_rows+":last"))}function removeRowAt(position){$(_rows).each(function(index){var row=$(this);if(index===position)row.remove()})}function updateRow(position,data){var row=$(_rows)[position];var cells=$("td",row);for(var field in data)if(data.hasOwnProperty(field))for(var index=
0;index<_metadata.length;index++)if(_metadata[index].field===field){cells.eq(index).html(data[field]);break}}function refreshTableHeader(){var headerRow="<tr>";for(var i=0;i<_metadata.length;i++){headerRow+="<th>"+_metadata[i].label;headerRow+="</th>"}headerRow+="</tr>";$(_thead+" tr").remove();$(_thead).append(headerRow);if(_sortable)sortableTable(_table)}function refreshTableBody(){$(_rows).remove();if(_filtered.length>0)for(var i=_start;i<_end;i++){var index=getUnfilteredIndex(i);appendRow(_data[index])}else for(var i=
_start;i<_end;i++)appendRow(_data[i]);if(_currentSelectedRowPage===_currentPage&&_currentSelecteRowIndex!==UNDEFINED_INDEX){var selectedRow=$(_rows)[_currentSelecteRowIndex];$(selectedRow).addClass(_style)}else _currentSelecteRowIndex=UNDEFINED_INDEX;if(_paginate)refreshPaginationView()}return{UNDEFINED_INDEX:UNDEFINED_INDEX,ASCENDING_ORDER:ASCENDING_ORDER,DESCENDING_ORDER:DESCENDING_ORDER,DEFAULT_PAGE_SIZE:DEFAULT_PAGE_SIZE,appendData:function(data){if(data){_data.push(data);resetFilters();updatePagination();
goToPage(_currentPage)}},removeData:function(index){if(validateIndex(index)){var arrayIndex=getArrayIndex(index);var position=getUnfilteredIndex(arrayIndex);_data.splice(position,1);if(position===_currentSelecteRowIndex)_currentSelecteRowIndex=UNDEFINED_INDEX;updatePagination();if(_currentPage>_totalPages)goToPage(_currentPage-1);else goToPage(_currentPage)}},updateData:function(index,data){if(validateIndex(index)&&data){var arrayIndex=getArrayIndex(index);var position=getUnfilteredIndex(arrayIndex);
for(var i=0;i<_metadata.length;i++){var key=_metadata[i].field;if(key&&data.hasOwnProperty(key))_data[position][key]=data[key]}updateRow(index,data)}},values:function(){return _data},valueAt:function(index){if(validateIndex(index)){var arrayIndex=getArrayIndex(index);var position=getUnfilteredIndex(arrayIndex);return _data[position]}return{}},selectedRowValue:function(){return this.valueAt(_currentSelecteRowIndex)},selectedRowIndex:function(){return _currentSelecteRowIndex},render:function(){refreshTableHeader();
goToPage(1)},filterData:function(filters){filter(filters);if(_filtered.length>0)setPageSize(_pageSize)},clearFilters:function(){resetFilters();setPageSize(_pageSize)},removeAll:function(){_data=[];refreshTableHeader();goToPage(1)}}}};
